1\. Write a program that creates a NumPy array containing 20 zeros, then reshape it to get a two-dimensional array with 5 rows and 4 columns. Print this array. Now assign to its middle area 1 to obtain an array whose the first and the last rows as well as the first and the last columns contain 0 and all others are 1. Print this array.

In [1]:
import numpy as np

array1d = np.zeros(20)
array2d = array1d.reshape(5, 4)
print(array2d)
array2d[1:-1, 1:-1] = 1
print(array2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


2\. Write a program that creates a NumPy array $x$ containing 11 equally spaced values from 0 to $2\pi$. Now compute two new arrays: $s=\sin x$ and $c=\cos x$. Finally compute and print the result of expression $s^2 + c^2$

In [5]:
import numpy as np

x = np.linspace(0, 2*np.pi, 11)
s = np.sin(x)
c = np.cos(x)
result = s**2 + c**2
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3\. Create a program that reads president heights form a file `presidents.csv` and store them into a NumPy array. Read only heights, without names. Then compute and print the smallest, the biggest and the mean height.

In [63]:
file_name = "presidents.csv"

txt = ['Garfield, 183', 'Obama, 185', 'Bush, 182', 'Reagan, 185', 'Kennedy, 185', 'Grant, 173', 'Taft, 182', 'Johnson, 192', 'Coolidge, 178', 'Arthur, 188', 'Bush, 188', 'Wilson, 180', 'Monroe, 183', 'Buchanan, 183', 'Roosevelt, 188', 'Johnson, 178', 'Cleveland, 180', 'Jackson, 185', 'McKinley, 170', 'Harrison, 168', 'Polk, 173', 'Taylor, 173', 'Truman, 175', 'Harding, 183', 'Buren, 168', 'Ford, 183', 'Clinton, 188', 'Carter, 177', 'Q_Adams, 171', 'Trump, 191', 'Jefferson, 189', 'Nixon, 182', 'Pierce, 178', 'Washington, 188', 'Lincoln, 193', 'Madison, 163', 'Hoover, 182', 'Roosevelt, 178', 'Adams, 170', 'Tyler, 183', 'Fillmore, 175', 'Harrison, 173', 'Hayes, 174', 'Eisenhower, 179']
with open(file_name, "w") as f:
    for s in txt:
        f.write(s + '\n')

import numpy as np

heights = np.arange(0)
with open(file_name, "r") as f:
  for line in f:
        data = line.strip().split(',')
        heights = np.append(heights, int(data[1]))
print(f'The smallest height: {np.min(heights)}')
print(f'The biggest height: {np.max(heights)}')
print(f'The mean height: {np.round(np.mean(heights), 1)}')

The smallest height: 163
The biggest height: 193
The mean height: 180.1


4\. Create a program that reads both president heights and names. Collect names in a list, do not use a NumPy array for them. Then compute the smallest, the biggest and median heights and print them with the corresponding names.

_Hint. Median is the value in the middle of a sorted array._

In [42]:
file_name = "presidents.csv"

txt = ['Garfield, 183', 'Obama, 185', 'Bush, 182', 'Reagan, 185', 'Kennedy, 185', 'Grant, 173', 'Taft, 182', 'Johnson, 192', 'Coolidge, 178', 'Arthur, 188', 'Bush, 188', 'Wilson, 180', 'Monroe, 183', 'Buchanan, 183', 'Roosevelt, 188', 'Johnson, 178', 'Cleveland, 180', 'Jackson, 185', 'McKinley, 170', 'Harrison, 168', 'Polk, 173', 'Taylor, 173', 'Truman, 175', 'Harding, 183', 'Buren, 168', 'Ford, 183', 'Clinton, 188', 'Carter, 177', 'Q_Adams, 171', 'Trump, 191', 'Jefferson, 189', 'Nixon, 182', 'Pierce, 178', 'Washington, 188', 'Lincoln, 193', 'Madison, 163', 'Hoover, 182', 'Roosevelt, 178', 'Adams, 170', 'Tyler, 183', 'Fillmore, 175', 'Harrison, 173', 'Hayes, 174', 'Eisenhower, 179']
with open(file_name, "w") as f:
    for s in txt:
        f.write(s + '\n')

import numpy as np

names = []
heights = np.arange(0)
with open(file_name, "r") as f:
  for line in f:
        data = line.strip().split(',')
        names.append(data[0])
        heights = np.append(heights, int(data[1]))
print(f'The smallest president: {names[np.argmin(heights)]}, his hight is {np.min(heights)}.')
print(f'The biggest president: {names[np.argmax(heights)]}, his hight is {np.max(heights)}.')
sorted_heights = np.sort(heights)
# On an array with an even length, the median is not uniquely determined
if len(heights) % 2 != 0:
  median = int(sorted_heights[int(len(sorted_heights) / 2)])
else:
  median = int((sorted_heights[int(len(sorted_heights) / 2)] + sorted_heights[int(len(sorted_heights) / 2 + 1)]) / 2)
indexes = np.where(heights == median)[0]
print(f'Presidensts with median height (that is {median}):', end=' ')
for index in indexes:
  if index == indexes[-1]:
    print(names[index], end='. ')
  else:
    print(names[index], end=', ')



The smallest president: Madison, his hight is 163.
The biggest president: Lincoln, his hight is 193.
Presidensts with median height (that is 182): Bush, Taft, Nixon, Hoover. 

5\. First run the above section to get a file "sleep.csv". This file contains three columns: sex, country and sleeping time. Create a program that reads this file converting the sleeping time from 'hh:mm' format to an integer numbers of minutes. Now print the answers to the following questions: What are the largest and the smallest sleeping time for males and females? In which country people sleep more? What is the average sleeping time?

In [74]:
file_name = "sleep.csv"

txt = ["Males, Belgium, 8:15","Males, Bulgaria, 9:08","Males, Germany, 8:08","Males, Estonia, 8:24","Males, Spain, 8:36","Males, France, 8:45","Males, Italy, 8:17","Males, Latvia, 8:35","Males, Lithuania, 8:28","Males, Poland, 8:21","Males, Slovenia, 8:18","Males, Finland, 8:22","Males, United Kingdom, 8:18","Males, Norway, 7:56","Females, Belgium, 8:34","Females, Bulgaria, 9:07","Females, Germany, 8:15","Females, Estonia, 8:26","Females, Spain, 8:32","Females, France, 8:55","Females, Italy, 8:19","Females, Latvia, 8:44","Females, Lithuania, 8:35","Females, Poland, 8:35","Females, Slovenia, 8:25","Females, Finland, 8:32","Females, United Kingdom, 8:27","Females, Norway, 8:10"]
with open(file_name, "w") as f:
    for s in txt:
        f.write(s + '\n')

import numpy as np

sex = []
country = []
time = np.arange(0, dtype=int)
with open(file_name, "r") as f:
  for line in f:
        data = line.strip().split(',')
        sex.append(data[0])
        country.append(data[1])
        time = np.append(time, int(data[2].split(':')[0]) * 60 + int(data[2].split(':')[1]))
print(f'Average sleeping time: {int(np.mean(time) // 60)} h {int(np.mean(time) % 60)} m')
males = np.arange(0)
females = np.arange(0)
for i in range(len(sex)):
  if sex[i] == 'Males':
    males = np.append(males, time[i])
  elif sex[i] == 'Females':
    females = np.append(females, time[i])
print(f'Largest sleeping time for males: {np.max(males) // 60} h {np.max(males) % 60} m')
print(f'Smallest sleeping time for males: {np.min(males) // 60} h {np.min(males) % 60} m')
print(f'Largest sleeping time for females: {np.max(females) // 60} h {np.max(females) % 60} m')
print(f'Smallest sleeping time for females: {np.min(females) // 60} h {np.min(females) % 60} m')
countries = list(set(country))
arr = np.zeros(len(countries) * 2).reshape(len(countries), 2)
for i in range(len(country)):
  for j in range(len(countries)):
    if country[i] == countries[j]:
      arr[j, 0] += time[i]
      arr[j, 1] += 1
mean_time = arr[:, 0] / arr[:, 1]
print(f'People sleep more in {countries[np.argmax(mean_time)]}: mean sleep time is {np.max(mean_time) // 60} h {np.max(mean_time) % 60} m')


Average sleeping time: 8 h 28 m
Largest sleeping time for males: 9 h 8 m
Smallest sleeping time for males: 7 h 56 m
Largest sleeping time for females: 9 h 7 m
Smallest sleeping time for females: 8 h 10 m
People sleep more in  Bulgaria: mean sleep time is 9.0 h 7.5 m
