1\. Create a function that computes a matrix trace: $\textrm{Tr} A$.

In [37]:
import numpy as np


def tr(A):
  res = 0
  for i in range(len(A[0])):
    res += A[i, i]
  return res


matrix = np.array([[1, 456489, 231658], [3213546, 1, 897564], [231354, 479845, 1]], dtype=float)
print(f'Trace of matrix: {tr(matrix)}')

Trace of matrix: 3.0


2\. Create functions that perform matrix - matrix addition and subtraction: $C = A \pm B$.

In [36]:
import numpy as np


def sum(A, B, sign):
  res = np.zeros((len(A), len(A)))
  for i in range(len(A[0])):
         for j in range(len(A[0])):
                  if sign == '+':
                    res[i][j] = A[i][j] + B[i][j]
                  elif sign == '-':
                    res[i][j] = A[i][j] - B[i][j]
  return res


matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
matrix2 = np.ones((3, 3)) * 10
print(f'Summ: \n {sum(matrix1, matrix2, "-")}')

Summ: 
 [[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]


3\. Create a function that performs left vector - matrix multiplication: $\vec x A = \vec y$.

In [38]:
import numpy as np


def left_vector_matrix_multiplication(vector, matrix):
    result = np.zeros(len(vector))
    for i in range(len(vector)):
        for j in range(len(vector)):
            result[i] += vector[j] * matrix[j][i]
    return result


vector = np.array([1, 2, 3], dtype=float)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
result = left_vector_matrix_multiplication(vector, matrix)
print(f'Left vector multiplication: {result}')
print(np.dot(vector, matrix)) #  For insurance

Left vector multiplication: [30. 36. 42.]
[30. 36. 42.]


4\. Create a function that performs multiplication of a matrix by a scalar: $B = c A$.

In [33]:
import numpy as np


def multiply(A, c):
  for i in range(len(A[0])):
    for j in range(len(A[0])):
      A[i][j] *= c
  return A


matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
const = 0.5
print(f'Multiplication: \n {multiply(matrix, const)}')

Multiplication: 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


5\. Create a function that performs matrix - matrix multiplication: $C = A B$

In [47]:
import numpy as np


def matrix_multiply(matrix1, matrix2):
    m = len(matrix1)
    n = len(matrix1[0])
    p = len(matrix2[0])
    result = np.zeros((p, m))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result


matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[1, 3, 5], [7, 9, 11], [13, 17, 19]])

result = matrix_multiply(matrix1, matrix2)
print(f'Multiplication: \n {matrix_multiply(matrix1, matrix2)}')

Multiplication: 
 [[ 54.  72.  84.]
 [117. 159. 189.]
 [180. 246. 294.]]


6\. Create a function that generates an identity matrix of a given size. You can not solve the problem just by calling the defined above function `matrix_diag`.

In [46]:
import numpy as np


def generate_identity_matrix(size):
    identity_matrix = np.zeros((size, size))
    for i in range(size):
        identity_matrix[i][i] = 1
    return identity_matrix


size = 20
print(f'id: \n {generate_identity_matrix(size)}')

id: 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.

7\. Create functions that perform left and right multiplication of a matrix by a diagonal matrix.

In [51]:
import numpy as np


def matrix_multiply(matrix1, matrix2):
    m = len(matrix1)
    n = len(matrix1[0])
    p = len(matrix2[0])
    result = np.zeros((p, m))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result


def generate_identity_matrix(size):
    identity_matrix = np.zeros((size, size))
    for i in range(size):
        identity_matrix[i][i] = 1
    return identity_matrix


def f(matrix, side):
  if side == 'left':
    return matrix_multiply(generate_identity_matrix(len(matrix[0])), matrix)
  elif side == 'right':
    return matrix_multiply(matrix, generate_identity_matrix(len(matrix[0])))


A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Left: \n {f(A, "left")}')
print(f'Right: \n {f(A, "right")}')

Left: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Right: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


8\. Create a function that generates a zero matrix. You can not solve the problem just by calling the defined above function `matrix_diag`.

In [56]:
def zero(size):
  return [[0.0] * size] * size


print(f'Zero matrix: {zero(3)}')

Zero matrix: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
